name: Run CI Suite
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    
    - name: bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        
    - name: rspec
      run: bundle exec rspec -fd
    
    - name: rubocop
      run: bundle exec rubocop

  
